# -*- coding: utf-8 -*-
"""test_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P43WqmPyn_Q-Vux9ft7Q77WpgaEnmM1S
"""

from analysis import Analysis

def test_valid_github_api():
    analysis = Analysis("your_analysis_config")  # Replace "your_analysis_config" with the actual configuration
    repos_list = analysis.get_top_starred_repos()
    assert len(repos_list) > 0, 'Invalid List of Repositories'

def test_match_github_api():
    analysis = Analysis("your_analysis_config")  # Replace "your_analysis_config" with the actual configuration
    expected_repo = {
        "name": "Martinmejia/UofT_temp",
        "stars": 123
    }
    repos_list = analysis.get_top_starred_repos()

    # Assuming the order of repositories returned is consistent
    actual_repo = repos_list[0]

    # Compare each key-value pair
    for key, expected_value in expected_repo.items():
        actual_value = actual_repo[key]
        assert expected_value == actual_value